export const JOB_TITLES = [
    'Account Manager',
    'Assistant Commercial',
    'Business Developer',
    'CEO / Dirigeant',
    'Chef de Projet',
    'Chef des Ventes',
    'Commercial Sédentaire',
    'Commercial Terrain',
    'Consultant',
    'Directeur Commercial',
    'Directeur Marketing',
    'Entrepreneur',
    'Ingénieur d\'Affaires',
    'Key Account Manager',
    'Manager',
    'Responsable Administration des Ventes',
    'Responsable Marketing',
    'Sales Development Representative (SDR)',
    'Technico-Commercial',
    'Autre'
] as const;

export const SECTORS = [
    'Administration / Services Publics',
    'Aéronautique / Spatial',
    'Agroalimentaire',
    'Automobile',
    'Banque / Assurance',
    'BTP / Construction',
    'Chimie / Pharmacie',
    'Commerce / Distribution',
    'Conseil / Audit',
    'Éducation / Formation',
    'Énergie / Environnement',
    'Événementiel / Loisirs',
    'Hôtellerie / Restauration',
    'Immobilier',
    'Industrie',
    'Informatique / Tech / Télécoms',
    'Luxe / Mode / Cosmétique',
    'Marketing / Communication / Publicité',
    'Médias / Édition',
    'Santé / Médical',
    'Services aux Entreprises',
    'Transport / Logistique',
    'Autre'
] as const;
