-- Ajouter TOUTES les colonnes manquantes à la table leads

-- Colonnes de base
ALTER TABLE leads ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT 'Sans nom';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS company TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS contact_name TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS siret TEXT;

-- Colonnes d'adresse
ALTER TABLE leads ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS zip_code TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS country TEXT;

-- Colonnes de pipeline
ALTER TABLE leads ADD COLUMN IF NOT EXISTS stage TEXT NOT NULL DEFAULT 'new';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS value NUMERIC;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS probability INTEGER;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS closed_date TIMESTAMPTZ;

-- Colonnes de contenu
ALTER TABLE leads ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS next_actions JSONB DEFAULT '[]'::jsonb;

-- Colonnes de métadonnées
ALTER TABLE leads ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE leads ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE leads ADD COLUMN IF NOT EXISTS pipeline_id TEXT;